name: Build with Actions

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git
          pacboy: >-
            go:p gcc:p pkg-config:p gstreamer:p gst-plugins-base:p gst-plugins-good:p gst-plugins-bad:p gst-plugins-ugly:p
      - name: CI-Build
        run: |
          go build .
