name: Build with Actions

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git base-devel
          pacboy: >-
            go:p gstreamer:p gst-plugins-base:p gst-plugins-good:p gst-plugins-bad:p gst-plugins-ugly:p gst-libav:p gst-devtools:p gst-rtsp-server:p
      - name: CI-Build
        run: |
          go build .
